CREATE TABLE PROFESORES (
NUMPRO NUMBER(3),
NOMPRO VARCHAR2(25),
FNAPRO DATE,
JEFPRO NUMBER(3),
FINPRO DATE,
SALPRO NUMBER(7,2),
COMPRO NUMBER(7,2),
ESPPRO VARCHAR2(25),
PRIMARY KEY (NUMPRO),
FOREIGN KEY (JEFPRO) REFERENCES PROFESORES(NUMPRO)
);

CREATE TABLE CURSOS(
NUMCUR NUMBER(3),
TITCUR VARCHAR2(45),
PRECUR NUMBER(7,2),
EDICUR NUMBER(3),
HORCUR NUMBER(3),
FINCUR DATE,
FFICUR DATE,
CRECUR NUMBER(3),
NUMPRO NUMBER(3),
PRIMARY KEY (NUMCUR),
FOREIGN KEY (NUMPRO) REFERENCES PROFESORES(NUMPRO)
);

CREATE TABLE TIPOS_SALARIO(
TIPOSAL VARCHAR2(20),
INFERIOR NUMBER(4),
SUPERIOR NUMBER(4)
);

CREATE TABLE ALUMNOS(
NUMALU NUMBER(3),
NOMALU VARCHAR2(25),
DIRALU VARCHAR2(45),
CPOALU VARCHAR2 (5),
TELALU NUMBER(9),
EMAALU VARCHAR2(25),
PRIMARY KEY (NUMALU)
);

CREATE TABLE MATRICULADO(
NUMCUR NUMBER(3),
NUMALU NUMBER(3),
CALIFIC NUMBER(3,1),
PRIMARY KEY (NUMCUR, NUMALU),
FOREIGN KEY (NUMCUR) REFERENCES CURSOS (NUMCUR),
FOREIGN KEY (NUMALU) REFERENCES ALUMNOS(NUMALU)
);
